name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Rust
        shell: bash
        run: rustup update stable && rustup default stable

      - name: Run tests
        shell: bash
        run: make TEST_FLAGS="-j$(nproc)" test
